id: P009289
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:31:46.375730
source_metadata:
  id: bdr:W27933
  title: བཀའ་ཐང་གསེར་ཕྲེང
  author: ''
  volumes:
    6019d86731f84bfa8870a9a38a083619:
      image_group_id: I4533
      title: ''
      volume_number: 1
      total_pages: 798
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
