id: I9AACF7F8
legacy_id: P009289
ocr_import_info:
  bdrc_scan_id: W27933
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T07:28:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:13:17.763889+00:00'
last_modified: 2022-09-02 16:14:42.129334
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27933
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27933
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་ཐང་གསེར་ཕྲེང་།
  author: གཏེར་སྟོན་སངས་རྒྱས་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7428546946708736
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I4533:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4533
      total_pages: 798
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4533.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7428546946708736
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
