id: I9AACF7F8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:29:58+00:00'
last_modified: '2022-06-08T09:57:42.600431+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27933
  title: བཀའ་ཐང་གསེར་ཕྲེང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3F98:
      image_group_id: I4533
      title: ''
      total_pages: 798
      order: 1
      base_file: 3F98.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
